### ISSUE TITLE
doubt in input primer fasta files

### ISSUE THREAD

**Issue by balathl** [aakechin/cutPrimers#3]
Hi,

I have a adapter trimmed fastq files(R1 and R2 reads). My forward primer sequence is "TGTGCCAGCMGCCGCGGTAA" and reverse primer sequence is "TGGACTACHVGGGTWTCTAAT". With this info, how to use cutPrimers?

I assume the below fasta files needs to be parsed from the fastq files at 5' and 3' end of the R1 and R2 reads. How to do this? 
--primersFileR1_5, -pr15 - fasta-file with sequences of primers on the 5'-end of R1 reads
  --primersFileR2_5, -pr25 - fasta-file with sequences of primers on the 5'-end of R2 reads. Do not use this parameter if you have single-end reads
  --primersFileR1_3, -pr13 - fasta-file with sequences of primers on the 3'-end of R1 reads. It is not required. But if it is determined, -pr23 is necessary
  --primersFileR2_3, -pr23 - fasta-file with sequences of primers on the 3'-end of R2 reads

Any help is appreciated and i am curious to compare your tool with our sequencing provider in-house primerclipping results!

Best Regards,
Bala

**Comment by aakechin** [comment]
@balathl, thank for your comment! You need to create four fasta-files with your primer-sequences on the 5' and 3' ends of R1 and R2 reads. Because cutPrimers can not work with ambiguous letters (like W, H, V and W in your case), I can offer two ways.
**First** - to use argument error-number (--error-number, -err - number of errors (substitutions, insertions, deletions) that allowed during searching primer sequence in a read sequence. Default: 5). You can leave it as default (5 errors) or increase it and you will need to make 4 fasta-files:
**_primers_R1_5.fa_**
\>R
TGGACTACHVGGGTWTCTAAT
**_primers_R1_3.fa_** (reverse complement sequence of forward primer):
\>F_reverse_complement
TTACCGCGGCKGCTGGCACA
**_primers_R2_5.fa_**:
\>F
TGTGCCAGCMGCCGCGGTAA
**_primers_R2_3.fa_** (reverse complement sequence of reverse primer):
\>R_reverse_complement
ATTAGAWACCCBDGTAGTCCA
I think this way is the fastest and simplest. You can use it, if you don't need statistics about how each pair of primers is presented in your reads.

Another way is more complex and IMHO slower. You will need to split all you possible sequences onto all possible pairs of primers (2 for forward * 18 for reverse, totally 36 different pairs). I've created such 4 files for you. If it will be useful, I will upload this new script to the project.
[primers_Bala.zip](https://github.com/aakechin/cutPrimers/files/1822348/primers_Bala.zip)

Also, I would recommend you to check, if your primer sequences are really located on the ends of you reads. If they can be on some distance from the end, try to vary --primer-location-buffer argument (-plb - Buffer of primer location in the read from the end. Default: 10).

Do not hesitate to ask me again, if something will go wrong.

Best regards,
Andrey
