### ISSUE TITLE
parameters and efficiency

### ISSUE THREAD

**Issue by gonzalezem** [aakechin/cutPrimers#5]
Hi,
Here is what I do. I have 2 paired-end reads (740,134 reads each) with staggered degenerate primers:

Forward primers | Reverse primers
---: | ---:
CCTACGGGNGGCWGCAG | GACTACHVGGGTATCTAATCC
TCCTACGGGNGGCWGCAG | TGACTACHVGGGTATCTAATCC
ACCCTACGGGNGGCWGCAG | ACGACTACHVGGGTATCTAATCC
CTACCTACGGGNGGCWGCAG | CTAGACTACHVGGGTATCTAATCC

Staggered meaning that 1, 2 or 3 bases are added to the main primer (_e.g._ CCTACGGGNGGCWGCAG) to increase diversity in Illumina sequencing. I would need to cut these out from the fastq. So I prepared 2 fasta files with 4 primer sequences each and ran cutprimers.py:

```
python3 cutPrimers.py 
    -r1 $FWD_read \
    -r2 /$REV_read \
    -pr15 forward_primers.fa \
    -pr25 reverse_primers.fa \
    -tr1 trim.pair1.fastq.gz \
    -tr2 trim.pair2.fastq.gz \
    -utr1 untrimmed1.fastq.gz \
    -utr2 untrimmed2.fastq.gz \
    --error-number 10 \
    -stat trim.statistics.log \
    --primer3-absent \
    --primer-location-buffer 30 \
    --threads 1
```
A note on the parameters: 
`--error-number 10` to account for the 2 ambiguous nucleotides (N and W) + the few bases that are added in the beginning of the primer. I tried lowest values but a few good primers remained in the untrimmed output. 10 does the job fine
`--primer-location-buffer 30`  to limit the region searched (in hope to gain time)
`--threads 1` because the parameters I chose are really RAM demanding when I run in parallel.

Now I can't understand well the trim.statistics.log file. It shows stats for 4 primers only (when I was expecting 8), and the number of reads don't match my samples:

Primer | Total_number_of_reads | Number_without_any_errors | Number_with_sequencing_errors | Number_with_synthesis_errors
--- | --- | --- | --- | ---
3F | 599 | 0 | 1198 | 0
3R | 599 | 0 | 0 | 0
4F | 719215 | 0 | 1438430 | 0
4R | 719215 | 0 | 0 | 0

It seems to do the job well although it takes quite a lot of time and RAM (I am on a server and it uses 15 GB for a little more than 2 hours for 1 paired-end reads). Do you think my parameters are adapted to what I want to do? Thanks!

**Comment by aakechin** [comment]
@gonzalezem, I think, 10 errors is too much. What do you want to get, statistics of primers' location in the reads or trimmed reads, or both? If your primers had good quality, I'd recommend you to use error-number of 2 (only for ambiguous letters). If you get some untrimmed reads, could you send me such reads, so I will check, if there is some bug in cutPrimers.
For --primer-location-buffer I'd use 0, because this values means, that cutPrimers will search for primer sequences in the region from start to (length of the longest primer+this value). This value is mostly for primers at the 3'-end of reads, when the length of read is more than the length of amplicon, there will be primer sequence and then adapter sequence. Sorry, for ambiguous description of parameter. I fixed it in the README file.

**Comment by gonzalezem** [comment]
Hi,
Thanks for your answer. To answer your question, I thought we would be given the number of initial reads and the number of trimmed/untrimmed reads, just to make a basic ratio about how much is lost during the trimming. But that's not a big deal.
I used your parameters and it runs fine but I found a few reads which were in the untrimmed files although they contain the exact primers.
Here is my command:

```
python ${cutPrimerPath}/cutPrimers.py -r1 C6_R1.fastq.gz -r2 C6_R2.fastq.gz \
	-pr15 forward_primers.fa \
	-pr25 reverse_primers.fa \
	-tr1 trimmed_R1.fastq -tr2 trimmed_R2.fastq \
	-utr1 notTrimmed_R1.fastq -utr2 notTrimmed_R2.fastq \
	-stat statistics.log \
	--error-number 2 \
	--primer3-absent \
	--primer-location-buffer 0 \
	--threads 1
```
Here are the initial reads as well as a bash script that builds the primers and starts cutPrimers.py (to launch the test, change the _cutPrimerPath_ variable inside launch_test.sh and `bash launch_test.sh`:

[missed_primers.zip](https://github.com/aakechin/cutPrimers/files/2283063/missed_primers.zip)

I found several paired-end read inside the untrimmed output that should have been trimmed. I don't know whether there are many others, but here is an example:

**Forward read**
```
@M00833:661:000000000-BPJ6P:1:2108:15710:13358 1:N:0:TGCGGCGATA
ACCCTACGGGAGGCTGCAGGGAGCAAACAGGATTAGTTACCCCAATAGTCAGACCAAGTCTCTGCTACCGTATGCGGCGATAATCTCGTATGCCGTCTTCTGCTTGAAGAAAAAAAAAACGATAGCTGCGGACTAAGAAGTGGCGACTATCGCGCCAGCAGCCGCCGTGATAAGAAGGAGGCTCGTATCGTTGTTCTGCATTATTAGGAGAGAGTGCGGCGTAGGAGAAATCATAAGTGGGTGATAACAC
```

**Corresponding reverse read**
```
@M00833:661:000000000-BPJ6P:1:2108:15710:13358 2:N:0:TGCGGCGATA
GACTACTGGGGTATCTAATCCTGTTTGCTCCCTGCAGCCTCCCGTAGGGTTGTAGAACCATGTCGTCAGTGTAGATCTCGGTGGCCGCCGTATCATTAAAAAAAACGAAGCCTTTTGCGACTAGTGGGGTAATATCACATGCCTCTGCACTCATCGTATACTGTAACATAGGATGTAGATCGGGAGTTCCGGGGGTTGATATCCCTGACTAGTCTCGACGCCTCCGCGGCCTTCACGCCCACAGATTCTT
```
The forward read contains `ACCCTACGGGNGGCWGCAG` forward primer (named Sequence_3) and the corresponding reverse read contains `GACTACHVGGGTATCTAATCC` reverse primer (named Sequence_1).

**Comment by aakechin** [comment]
Ok, I see the problem. cutPrimers is adapted to cut primers from amplicons that should have certain pairs of primers. So, if it found primer R1 in the 1st read of pair, then it checks, if there is F1-primer in the 2nd read of pair. And only if it is true, it trims primer sequences in both reads. 
You can trim primer sequences in your reads sequentuelly, first, in the 1st reads of pairs, and then in the 2nd reads of pairs.

**Comment by aakechin** [comment]
Ok, I see the problem. cutPrimers was adapted for an amplicon-based NGS resequencing with gene panels. So it searches for matches of primers from R1_5 and R2_5 primers from input file. So, first primer from R1_5 file should be in the 1st read of reads pair and first primer from R2_5 file should be in the 2nd read of pair.

In your case you can use cutPrimers for files with R1 and R2 reads separately. Initially, trim primer sequences from R1-file and then from R2-file. But do not forget to use -r1, -utr1 and -pr15 parameters, again, instead of -r2, -utr2 and -pr25. After that, you can select matches of read pairs from files with trimmed R1 and R2 reads.

**Comment by aakechin** [comment]
Ability of cutting degenerate primer sequences was added! Hope, it will be useful.
